### PR TITLE
Why was JSON Viewer Awesome marked as malware by chrome?

### PR DESCRIPTION
**Pull request by jsskarthik7**
Why is the issues tab is disabled?

Can't use extension without explanation.

### CODE REVIEW

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
See: 

https://github.com/rbrahul/Awesome-JSON-Viewer/issues/61#issuecomment-708700144

https://github.com/rbrahul/Awesome-JSON-Viewer/issues/61#issuecomment-709072350

**Comment by rbrahul** [comment]
I have described several times already. Please find it here [https://github.com/rbrahul/Awesome-JSON-Viewer/issues/64](https://github.com/rbrahul/Awesome-JSON-Viewer/issues/64)

**Comment by jsskarthik7** [comment]
None of the links you posted are working.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
The critic was censored. Issues disappeared since deleted.



-----Original Message-----

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
The critic was censored. Issues disappeared since deleted.

**Comment by jsskarthik7** [comment]
Thanks for the response.

**Comment by muescha** [comment]
the links are not working, can you please explain again?

**Pull request closed without merging**
