### PR TITLE
Update URL pattern

### PR DESCRIPTION
**Pull request by MohamadKh75**
I just wanted to add `https://reactnative.directory` and I realize that the regex need to be updated!

### CODE REVIEW

**Comment by MohamadKh75** [comment]
Thanks!
And, where can I have this in my browser? (new release)

**Comment by rbrahul** [comment]
It's not released yet, I will update the package along with some other changes. You will get it in the next version very soon.

**Comment by MohamadKh75** [comment]
Hey

Any update on the new release?

**Comment by MohamadKh75** [comment]
Ping @rbrahul

**Pull request merged**
